// Package storage defines the interface between the Tether engine and the
// backends that hold uploaded files. Built-in adapters live in the local and
// s3 subpackages; pass one to Engine.UseStorage.
package storage

import (
	"context"
	"net/http"
	"time"
)

// UploadOptions configures an upload URL created by StorageCtx.GetUploadURL.
type UploadOptions struct {
	// MaxBytes is the largest file the upload accepts. Zero means 20 MB.
	MaxBytes int64
	// ExpiresIn is how long the upload URL stays valid. Zero means 15
	// minutes.
	ExpiresIn time.Duration
}

// UploadInfo is returned by StorageCtx.GetUploadURL.
type UploadInfo struct {
	// FileID identifies the file once uploaded. Store it to refer to the file
	// later.
	FileID string `json:"fileID"`
	// UploadURL is the path the client sends the file to in a PUT request.
	UploadURL string `json:"uploadURL"`
}

// StorageAdapter stores file contents for the engine. The engine keeps file
// metadata, tokens and access checks in its own tables, so an adapter only
// reads, writes and deletes bytes by file ID. File IDs are generated by the
// engine.
type StorageAdapter interface {
	// UploadStream stores the body of r as the file fileID. The body is
	// already limited to the upload's maximum size.
	UploadStream(ctx context.Context, fileID string, contentType string, r *http.Request) error
	// ServeFile writes the file fileID to w, or redirects to where it can be
	// downloaded. The engine sets Content-Type and Content-Disposition
	// beforehand.
	ServeFile(fileID string, w http.ResponseWriter, r *http.Request) error
	// Delete removes the file fileID. If the file does not exist, it should
	// return nil or an error wrapping os.ErrNotExist; for any other error the
	// engine keeps the file's record and retries in a later cleanup.
	Delete(fileID string) error
	// Name identifies the adapter, such as "tether/storage/s3". It is saved
	// with each file so files can be traced to the backend that holds them.
	Name() string
}
