// Package storage defines the interface between the Tether engine and the
// backends that hold uploaded files. Built-in adapters live in the local and
// s3 subpackages; pass one to Engine.UseStorage.
package storage

import (
	"context"
	"net/http"
	"time"
)

const (
	defaultMaxBytes  int64 = 20 * 1024 * 1024
	defaultExpiresIn       = 15 * time.Minute
)

// uploadLimits is filled in by [UploadOption] values. A zero field selects
// the built-in default when the limits are resolved.
type uploadLimits struct {
	maxBytes  int64
	expiresIn time.Duration
}

// UploadOption configures an upload URL created by StorageCtx.GetUploadURL.
// The same options may be passed to a storage adapter constructor as the
// defaults for every upload from that adapter.
type UploadOption func(*uploadLimits)

// WithMaxBytes sets the largest file the upload accepts. Zero selects the
// built-in default of 20 MB.
func WithMaxBytes(n int64) UploadOption {
	return func(cfg *uploadLimits) {
		cfg.maxBytes = n
	}
}

// WithExpiresIn sets how long the upload URL stays valid. Zero selects the
// built-in default of 15 minutes.
func WithExpiresIn(d time.Duration) UploadOption {
	return func(cfg *uploadLimits) {
		cfg.expiresIn = d
	}
}

// EffectiveUploadLimits applies defaults and then opts, in order. Nil options
// are ignored. A zero size or lifetime selects the built-in default of 20 MB
// or 15 minutes, including when a later option clears an earlier one.
func EffectiveUploadLimits(defaults []UploadOption, opts []UploadOption) (maxBytes int64, expiresIn time.Duration) {
	cfg := uploadLimits{}
	for _, opt := range defaults {
		if opt != nil {
			opt(&cfg)
		}
	}
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}
	if cfg.maxBytes == 0 {
		cfg.maxBytes = defaultMaxBytes
	}
	if cfg.expiresIn == 0 {
		cfg.expiresIn = defaultExpiresIn
	}
	return cfg.maxBytes, cfg.expiresIn
}

// UploadInfo is returned by StorageCtx.GetUploadURL.
type UploadInfo struct {
	// FileID identifies the file once uploaded. Store it to refer to the file
	// later.
	FileID string `json:"fileID"`
	// UploadURL is the path the client sends the file to in a PUT request.
	UploadURL string `json:"uploadURL"`
}

// StorageAdapter stores file contents for the engine. The engine keeps file
// metadata, tokens and access checks in its own tables, so an adapter only
// reads, writes and deletes bytes by file ID. File IDs are generated by the
// engine.
type StorageAdapter interface {
	// UploadStream stores the body of r as the file fileID. The body is
	// already limited to the upload's maximum size.
	UploadStream(ctx context.Context, fileID string, contentType string, r *http.Request) error
	// ServeFile writes the file fileID to w, or redirects to where it can be
	// downloaded. The engine sets Content-Type and Content-Disposition
	// beforehand.
	ServeFile(fileID string, w http.ResponseWriter, r *http.Request) error
	// Delete removes the file fileID. If the file does not exist, it should
	// return nil or an error wrapping os.ErrNotExist; for any other error the
	// engine keeps the file's record and retries in a later cleanup.
	Delete(fileID string) error
	// Name identifies the adapter, such as "tether/storage/s3". It is saved
	// with each file so files can be traced to the backend that holds them.
	Name() string
	// DefaultUploadOptions returns the upload options passed to the adapter's
	// constructor. StorageCtx.GetUploadURL applies these first, then any
	// options passed at the call. Return nil to keep the built-in defaults of
	// 20 MB and 15 minutes.
	DefaultUploadOptions() []UploadOption
}
