// Package storage defines the interface between the Tether engine and the
// backends that hold uploaded files. Built-in adapters live in the local and
// s3 subpackages; pass one to Engine.SetStorage.
package storage

import (
	"context"
	"net/http"
	"time"
)

const (
	defaultMaxBytes          int64 = 20 * 1024 * 1024
	defaultExpiresIn               = 15 * time.Minute
	defaultPublic                  = false
	defaultDownloadExpiresIn       = 15 * time.Minute
)

// uploadLimits is filled in by [UploadOption] values. A zero field selects
// the built-in default when the limits are resolved.
type uploadLimits struct {
	maxBytes          int64
	expiresIn         time.Duration
	downloadExpiresIn time.Duration
	public            bool
}

// UploadOption configures an upload created by StorageCtx.GetUploadURL or
// StorageCtx.PutFile. The same options may be passed to Engine.SetStorage as
// the defaults for every upload. PutFile honors Public and ignores
// WithMaxBytes and WithExpiresIn.
type UploadOption func(*uploadLimits)

// WithMaxBytes sets the largest file the upload accepts. Zero selects the
// built-in default of 20 MB.
func WithMaxBytes(n int64) UploadOption {
	return func(cfg *uploadLimits) {
		cfg.maxBytes = n
	}
}

// WithExpiresIn sets how long the upload URL stays valid. Zero selects the
// built-in default of 15 minutes.
func WithExpiresIn(d time.Duration) UploadOption {
	return func(cfg *uploadLimits) {
		cfg.expiresIn = d
	}
}

// WithDownloadExpiresIn sets how long the download URL stays valid. Zero selects the
// built-in default of 15 minutes.
func WithDownloadExpiresIn(d time.Duration) UploadOption {
	return func(cfg *uploadLimits) {
		cfg.downloadExpiresIn = d
	}
}

// Public marks the file public. A public file can be read at
// {basePath}/public/{fileID} without a download token. Files are private
// unless Public is passed here or to Engine.SetStorage. There is no option
// that turns publicity back off.
func Public() UploadOption {
	return func(cfg *uploadLimits) {
		cfg.public = true
	}
}

// EffectiveUploadLimits applies defaults and then opts, in order. Nil options
// are ignored. A zero size or lifetime selects the built-in default of 20 MB
// or 15 minutes, including when a later option clears an earlier one.
// public is true when [Public] was among the options. defaults are the
// options passed to Engine.SetStorage.
func EffectiveUploadLimits(defaults []UploadOption, opts []UploadOption) (maxBytes int64, expiresIn time.Duration, downloadExpiresIn time.Duration, public bool) {
	cfg := uploadLimits{}
	for _, opt := range defaults {
		if opt != nil {
			opt(&cfg)
		}
	}
	for _, opt := range opts {
		if opt != nil {
			opt(&cfg)
		}
	}
	if cfg.maxBytes == 0 {
		cfg.maxBytes = defaultMaxBytes
	}
	if cfg.expiresIn == 0 {
		cfg.expiresIn = defaultExpiresIn
	}
	if cfg.downloadExpiresIn == 0 {
		cfg.downloadExpiresIn = defaultDownloadExpiresIn
	}
	if cfg.public == false {
		cfg.public = defaultPublic
	}
	return cfg.maxBytes, cfg.expiresIn, cfg.downloadExpiresIn, cfg.public
}

// UploadInfo is returned by StorageCtx.GetUploadURL.
type UploadInfo struct {
	// FileID identifies the file once uploaded. Store it to refer to the file
	// later.
	FileID string `json:"fileID"`
	// UploadURL is the path the client sends the file to in a PUT request.
	UploadURL string `json:"uploadURL"`
}

// StorageAdapter stores file contents for the engine. The engine keeps file
// metadata, tokens and access checks in its own tables, so an adapter only
// reads, writes and deletes bytes by file ID. File IDs are generated by the
// engine.
type StorageAdapter interface {
	// UploadStream stores the file fileID.
	//
	// Adapters must read the file from r.Body. The engine has already
	// wrapped that body to enforce the upload's size limit.
	//
	// r.ContentLength can be -1 for chunked uploads. The S3 adapter passes
	// that value straight through to AWS, and the engine stores it as the
	// file size.
	UploadStream(ctx context.Context, fileID string, contentType string, r *http.Request) error
	// ServeFile writes the file fileID to w, or redirects to where it can be
	// downloaded. The engine sets Content-Type, Content-Disposition, and
	// X-Content-Type-Options beforehand.
	ServeFile(fileID string, w http.ResponseWriter, r *http.Request) error
	// Delete removes the file fileID. If the file does not exist, it should
	// return nil or an error wrapping os.ErrNotExist; for any other error the
	// engine keeps the file's record and retries in a later cleanup.
	Delete(ctx context.Context, fileID string) error
	// Name identifies the adapter, such as "tether/storage/s3". It is saved
	// with each file so files can be traced to the backend that holds them.
	Name() string
}
